<a href="https://colab.research.google.com/github/xehau/xehau_lessons/blob/master/PyCUDA_test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install -U pycuda

     |████████████████████████████████| 1.6MB 7.7MB/s 
     |████████████████████████████████| 71kB 9.5MB/s 
     |████████████████████████████████| 481kB 33.7MB/s 
  Created wheel for pycuda: filename=pycuda-2020.1-cp37-cp37m-linux_x86_64.whl size=621061 sha256=6e9b71d86c9fc6113eea79e935a216b1892000679a5543e1ac1a823a1d220ea4
  Stored in directory: /root/.cache/pip/wheels/8f/78/d1/5bb826f81d9d490297a348d818ff3ee6dd6f2075b06dde6ea0
  Created wheel for pytools: filename=pytools-2021.1-py2.py3-none-any.whl size=60415 sha256=666e87cd283f5351d6993b6cedc2e93627c830bcc692356b671ee5ac66df4523
  Stored in directory: /root/.cache/pip/wheels/5d/85/10/7da05d77b47f2cb503e5c4185ba82187d0b6b6736b3c6641e0
  Created wheel for mako: filename=Mako-1.1.4-py2.py3-none-any.whl size=75675 sha256=df4968a6735b0e4d3fe18c38887a34a4e7b43980cdfd05dbed07b35a367dd426
  Stored in directory: /root/.cache/pip/wheels/ad/10/d3/aeb26e20d19045e2a68e5d3cbb57432e11b5d9c92c99f98d47
Successfully built pycuda pytools mako


In [2]:
import numpy as np
import pycuda.autoinit
import pycuda.driver as cuda
import pycuda.gpuarray as gpuarray

# 乱数配列を生成→GPUのメモリーを割いてデータを渡す
rand_array = np.random.randn(5, 5)
array_gpu = gpuarray.to_gpu(rand_array)
# 生成した配列の2乗の結果を取得
result = (array_gpu ** 2).get()

print(result)

[[0.53492861 0.04426081 1.63273254 1.11164239 0.46195167]
 [0.99334377 0.66040902 0.16451304 0.07750924 0.10465339]
 [0.00571038 3.00538186 0.03618899 0.29157811 1.97878257]
 [0.42903742 0.28939349 0.26890802 1.20013479 1.819374  ]
 [0.45631428 2.58672988 2.68135191 1.04792621 2.78537479]]
