<a href="https://colab.research.google.com/github/xehau/xehau_lessons/blob/master/tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##### Copyright 2020 The TensorFlow Authors.

In [ ]:
#@title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# テンソルの基礎

<table class="tfo-notebook-buttons" align="left">
  <td><a target="_blank" href="https://www.tensorflow.org/guide/tensor"><img src="https://www.tensorflow.org/images/tf_logo_32px.png"> TensorFlow.orgで表示</a></td>
  <td><a target="_blank" href="https://colab.research.google.com/github/tensorflow/docs-l10n/blob/master/site/ja/guide/tensor.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png"> Google Colab で実行</a></td>
  <td><a target="_blank" href="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/tensor.ipynb"><img src="https://www.tensorflow.org/images/GitHub-Mark-32px.png">GitHub でソースを表示{</a></td>
  <td><a href="https://storage.googleapis.com/tensorflow_docs/docs-l10n/site/ja/guide/tensor.ipynb"><img src="https://www.tensorflow.org/images/download_logo_32px.png">ノートブックをダウンロード/a0}</a></td>
</table>

In [ ]:
import tensorflow as tf
import numpy as np

テンソルは `dtype` と呼ばれる均一型の多次元配列です。サポートされているすべての `dtypes` は、`tf.dtypes.DType` で確認できます。

[NumPy](https://numpy.org/devdocs/user/quickstart.html) で言えば、テンソルは `np.arrays`（のようなもの）とすることができます。

すべてのテンソルは、Python の数値や文字列と同じように不変です。つまり、テンソルのコンテンツを更新することは不可能で、新しいテンソルのみを作成できます。


## 基礎

基本的なテンソルを作成してみましょう。

次は、「スカラー」または「階数 0」のテンソルです。スカラーには単一の値のみが含まれ、「軸」は存在しません。

In [ ]:
# This will be an int32 tensor by default; see "dtypes" below.
rank_0_tensor = tf.constant(4)
print(rank_0_tensor)

tf.Tensor(4, shape=(), dtype=int32)


「ベクトル」または「階数 1」テンソルは、値のリストとして考えられます。1 ベクトルは 1 つの軸です。

In [ ]:
# Let's make this a float tensor.
rank_1_tensor = tf.constant([2.0, 3.0, 4.0])
print(rank_1_tensor)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


「行列」または「階数 2」テンソルには軸が 2 つあります。

In [ ]:
# If we want to be specific, we can set the dtype (see below) at creation time
rank_2_tensor = tf.constant([[1, 2],
                             [3, 4],
                             [5, 6]], dtype=tf.float16)
print(rank_2_tensor)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


<table>
<tr>
  <th>スカラー, 形状: <code>[]</code>
</th>
  <th>ベクトル, 形状: <code>[3]</code>
</th>
  <th>行列, 形状: <code>[3, 2]</code>
</th>
</tr>
<tr>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/scalar.png?raw=1" alt="A scalar, the number 4">
</td>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/vector.png?raw=1" alt="The line with 3 sections, each one containing a number.">
</td>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/matrix.png?raw=1" alt="A 3x2 grid, with each cell containing a number.">
</td>
</tr>
</table>


テンソルにはさらに軸があります。次は、3 軸のテンソルです。

In [ ]:
# There can be an arbitrary number of
# axes (sometimes called "dimensions")
rank_3_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],])
                    
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


3 軸以上のテンソルを視覚化する方法はたくさんあります。

<table>
<tr>
  <th colspan="3">3 軸テンソル, 形状: <code>[3, 2, 5]</code>
</th>
</tr>
<tr>
</tr>
<tr>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/3-axis_numpy.png?raw=1">
</td>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/3-axis_front.png?raw=1">
</td>
  <td>    <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/3-axis_block.png?raw=1">
</td>
</tr>
</table>

`np.array` または `tensor.numpy` メソッドを使用して、テンソルを NumPy 配列に変換できます。

In [ ]:
np.array(rank_2_tensor)

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

In [ ]:
rank_2_tensor.numpy()

array([[1., 2.],
       [3., 4.],
       [5., 6.]], dtype=float16)

テンソルには、通常、浮動小数点型や整数型が含まれますが、次のようなほかの型も含まれます。

- 複素数
- 文字列

基本の `tf.Tensor` クラスには、「矩形」を成すテンソルが必要です。つまり各要素は、各軸に沿って同じサイズになります。ただし、次のように、異なる形状を処理できる特殊なテンソルもあります。

- 不規則（以下の [RaggedTensor](#ragged_tensors) を参照）
- スパース（以下の [SparseTensor](#sparse_tensors) を参照）

テンソルには、加算、要素ごとの乗算、および行列の乗算などの基本的な計算を実行できます。

In [ ]:
a = tf.constant([[1, 2],
                 [3, 4]])
b = tf.constant([[1, 1],
                 [1, 1]]) # Could have also said `tf.ones([2,2])`

print(tf.add(a, b), "\n")
print(tf.multiply(a, b), "\n")
print(tf.matmul(a, b), "\n")

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



In [ ]:
print(a + b, "\n") # element-wise addition
print(a * b, "\n") # element-wise multiplication
print(a @ b, "\n") # matrix multiplication

tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32) 

tf.Tensor(
[[3 3]
 [7 7]], shape=(2, 2), dtype=int32) 



テンソルはあらゆる種類の演算に使用されます。

In [ ]:
c = tf.constant([[4.0, 5.0], [10.0, 1.0]])

# Find the largest value
print(tf.reduce_max(c))
# Find the index of the largest value
print(tf.argmax(c))
# Compute the softmax
print(tf.nn.softmax(c))

tf.Tensor(10.0, shape=(), dtype=float32)
tf.Tensor([1 0], shape=(2,), dtype=int64)
tf.Tensor(
[[2.6894143e-01 7.3105860e-01]
 [9.9987662e-01 1.2339458e-04]], shape=(2, 2), dtype=float32)


## 形状について

テンソルには形状があり、次のような用語が使用されます。

- **形状**: テンソルの各次元の長さ（要素の数）。
- **階数**: テンソルの次元数。スカラーは階数 0、ベクトルは階数 1、行列は階数 2 となります。
- **軸**または**次元**: テンソルの特定の次元。
- **サイズ**: テンソル内の項目の総数。生成された形状ベクトル


注意: 「2 次元のテンソル」と記述されることもありますが、階数 2 のテンソルは、通常 2 次元形状ではありません。

テンソルと `tf.TensorShape` オブジェクトには、次にアクセスするための便利なプロパティがあります。

In [ ]:
rank_4_tensor = tf.zeros([3, 2, 4, 5])

<table>
<tr>
  <th colspan="2">階数 4 テンソル, 形状: <code>[3, 2, 4, 5]</code>
</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/shape.png?raw=1" alt="A tensor shape is like a vector.">
</td>
<td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/4-axis_block.png?raw=1" alt="A 4-axis tensor">
</td>
  </tr>
</table>


In [ ]:
print("Type of every element:", rank_4_tensor.dtype)
print("Number of dimensions:", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along the last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (3*2*4*5): ", tf.size(rank_4_tensor).numpy())

Type of every element: <dtype: 'float32'>
Number of dimensions: 4
Shape of tensor: (3, 2, 4, 5)
Elements along axis 0 of tensor: 3
Elements along the last axis of tensor: 5
Total number of elements (3*2*4*5):  120


軸は通常、そのインデックスで参照されますが、それぞれの意味を常に把握しておく必要があります。多くの場合、軸はグローバルからローカルに順序付けられています。バッチ軸を先頭に、空間次元、そして最後に各位置の特徴量が続きます。こうすることで、特徴ベクトルは連続したメモリ領域となります。

<table>
<tr>
<th>典型的な軸の順序</th>
</tr>
<tr>
    <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/shape2.png?raw=1" alt="Keep track of what each axis is. A 4-axis tensor might be: Batch, Width, Height, Freatures">
</td>
</tr>
</table>

## インデックス作成

### 単軸のインデックス作成

TensorFlow は、[Python でのリストまたは文字列のインデックス](https://docs.python.org/3/tutorial/introduction.html#strings)と同様の標準的な Python インデックスルールや numpy インデックスの基本ルールを使用しています。

- インデックスは `0` から開始
- 負のインデックスは後ろ側から逆順に数える
- スライスにコロン `:` を使用 -  `start:stop:step`


In [ ]:
rank_1_tensor = tf.constant([0, 1, 1, 2, 3, 5, 8, 13, 21, 34])
print(rank_1_tensor.numpy())

[ 0  1  1  2  3  5  8 13 21 34]


スカラーを使用してインデックスを作成すると、次元が削除されます。

In [ ]:
print("First:", rank_1_tensor[0].numpy())
print("Second:", rank_1_tensor[1].numpy())
print("Last:", rank_1_tensor[-1].numpy())

First: 0
Second: 1
Last: 34


`:` スライスでインデックスを作成すると、次元が維持されます。

In [ ]:
print("Everything:", rank_1_tensor[:].numpy())
print("Before 4:", rank_1_tensor[:4].numpy())
print("From 4 to the end:", rank_1_tensor[4:].numpy())
print("From 2, before 7:", rank_1_tensor[2:7].numpy())
print("Every other item:", rank_1_tensor[::2].numpy())
print("Reversed:", rank_1_tensor[::-1].numpy())

Everything: [ 0  1  1  2  3  5  8 13 21 34]
Before 4: [0 1 1 2]
From 4 to the end: [ 3  5  8 13 21 34]
From 2, before 7: [1 2 3 5 8]
Every other item: [ 0  1  3  8 21]
Reversed: [34 21 13  8  5  3  2  1  1  0]


### 多軸のインデックス作成

階数の高いテンソルは、複数のインデックスを渡してインデックス化されます。

単軸と全く同じルールが各軸に個別に適用されます。

In [ ]:
print(rank_2_tensor.numpy())

[[1. 2.]
 [3. 4.]
 [5. 6.]]


各インデックスに整数を渡すと、結果はスカラーになります。

In [ ]:
# Pull out a single value from a 2-rank tensor
print(rank_2_tensor[1, 1].numpy())

4.0


整数とスライスを任意に組み合わせてインデックスを作成することができます。

In [ ]:
# Get row and column tensors
print("Second row:", rank_2_tensor[1, :].numpy())
print("Second column:", rank_2_tensor[:, 1].numpy())
print("Last row:", rank_2_tensor[-1, :].numpy())
print("First item in last column:", rank_2_tensor[0, -1].numpy())
print("Skip the first row:")
print(rank_2_tensor[1:, :].numpy(), "\n")

Second row: [3. 4.]
Second column: [2. 4. 6.]
Last row: [5. 6.]
First item in last column: 2.0
Skip the first row:
[[3. 4.]
 [5. 6.]] 



次は、3 軸テンソルを使用した例です。

In [ ]:
print(rank_3_tensor[:, :, 4])

tf.Tensor(
[[ 4  9]
 [14 19]
 [24 29]], shape=(3, 2), dtype=int32)


<table>
<tr>
<th colspan="2">バッチ内の各例のすべての位置で最後の特徴量を選択する</th>
</tr>
<tr>
    <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/index1.png?raw=1" alt="A 3x2x5 tensor with all the values at the index-4 of the last axis selected.">
</td>
      <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/index2.png?raw=1" alt="The selected values packed into a 2-axis tensor.">
</td>
</tr>
</table>

## 形状の操作

テンソルの形状変更は非常に便利です。


In [ ]:
# Shape returns a `TensorShape` object that shows the size on each dimension
var_x = tf.Variable(tf.constant([[1], [2], [3]]))
print(var_x.shape)

(3, 1)


In [ ]:
# You can convert this object into a Python list, too
print(var_x.shape.as_list())

[3, 1]


テンソルを新しい形状に変更できます。<code>tf.reshape</code> 演算は、基盤のデータを複製する必要がないため、素早く簡単に行えます。

In [ ]:
# We can reshape a tensor to a new shape.
# Note that we're passing in a list
reshaped = tf.reshape(var_x, [1, 3])

In [ ]:
print(var_x.shape)
print(reshaped.shape)

(3, 1)
(1, 3)


データはレイアウトをメモリに維持したまま、同じデータにポイントする新しいテンソルが要求された形状で作成されます。TensorFlow は C 形式の「行優先」メモリ順序付けを使用しており、右端のインデックスの増分は、メモリ内の 1 ステップに相当します。

In [ ]:
print(rank_3_tensor)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


テンソルをフラット化すると、どの順序jでメモリにレイアウトされているかを確認できます。

In [ ]:
# A `-1` passed in the `shape` argument says "Whatever fits".
print(tf.reshape(rank_3_tensor, [-1]))

tf.Tensor(
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29], shape=(30,), dtype=int32)


通常、` tf.reshape ` の唯一合理的な使用は、隣接する軸を結合または分割する（または `1` を追加/削除する）ことです。

この 3x2x5 のテンソルでは、スライスは混合しないため、(3x2)x5 または 3x(2x5) に形状を変更するのが合理的です。

In [ ]:
print(tf.reshape(rank_3_tensor, [3*2, 5]), "\n")
print(tf.reshape(rank_3_tensor, [3, -1]))

tf.Tensor(
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]], shape=(6, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]], shape=(3, 10), dtype=int32)


<table>
<th colspan="3"> 形状変更の成功例。</th>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-before.png?raw=1" alt="A 3x2x5 tensor">
</td>
  <td>   <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-good1.png?raw=1" alt="The same data reshaped to (3x2)x5">
</td>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-good2.png?raw=1" alt="The same data reshaped to 3x(2x5)">
</td>
</tr>
</table>


形状変更は要素の総数が等しい新しい形状で「機能」しますが、軸の順を守らなければ役に立ちません。

`tf.reshape` では軸の交換は機能しないため、それを行うには `tf.transpose` が必要です。


In [ ]:
# Bad examples: don't do this

# You can't reorder axes with reshape.
print(tf.reshape(rank_3_tensor, [2, 3, 5]), "\n") 

# This is a mess
print(tf.reshape(rank_3_tensor, [5, 6]), "\n")

# This doesn't work at all
try:
  tf.reshape(rank_3_tensor, [7, -1])
except Exception as e:
  print(f"{type(e).__name__}: {e}")

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]], shape=(2, 3, 5), dtype=int32) 

tf.Tensor(
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]], shape=(5, 6), dtype=int32) 

InvalidArgumentError: Input to reshape is a tensor with 30 values, but the requested shape requires a multiple of 7 [Op:Reshape]


<table>
<th colspan="3">形状変更の失敗例。</th>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-bad.png?raw=1" alt="You can't reorder axes, use tf.transpose for that">   </td>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-bad4.png?raw=1" alt="Anything that mixes the slices of data together is probably wrong.">
</td>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/reshape-bad2.png?raw=1" alt="The new shape must fit exactly.">
</td>
</tr>
</table>

不完全に指定された形状を実行することができます。その形状には `None`（次元の長さが不明）が含まれているか、形状が `None`（テンソルの階数が不明）であるかのいずれかです。

[tf.RaggedTensor](#ragged_tensors) を除き、これは TensorFlow の象徴的なグラフ構築 API の文脈で発生します。

- [tf.function](function.ipynb)
- [Keras 関数型 API](keras/functional.ipynb)


## `DTypes` をさらに詳しく

`tf.Tensor` のデータ型を検査するには、`Tensor.dtype` プロパティを使用します。

Python オブジェクトから `tf.Tensor` を作成する場合、オプションとしてデータ型を指定できます。

指定しない場合は、TensorFlow によってデータを表すデータ型が選択されます。TensorFlow は Python の整数値を `tf.int32` と Python 浮動小数点数を `tf.float32` に変換します。そうでない場合は、TensorFlow は NumPy が配列に変換する場合と同じルールを使用します。

型から型にキャストすることができます。

In [ ]:
the_f64_tensor = tf.constant([2.2, 3.3, 4.4], dtype=tf.float64)
the_f16_tensor = tf.cast(the_f64_tensor, dtype=tf.float16)
# Now, let's cast to an uint8 and lose the decimal precision
the_u8_tensor = tf.cast(the_f16_tensor, dtype=tf.uint8)
print(the_u8_tensor)

tf.Tensor([2 3 4], shape=(3,), dtype=uint8)


## ブロードキャスト

ブロードキャストは、[NumPy の相当する機能](https://numpy.org/doc/stable/user/basics.html)から得た概念です。簡単に言えば、ある条件下において、より小さなテンソルに複合演算を実行する場合、より大きなテンソルに適合するように自動的に「引き延ばされる」ということです。

最も単純で一般的な事例としては、テンソルをスカラーに加算または乗算する場合が挙げられます。その場合、スカラーはもう片方の引数と同じ形状になるようにブロードキャストされます。 

In [ ]:
x = tf.constant([1, 2, 3])

y = tf.constant(2)
z = tf.constant([2, 2, 2])
# All of these are the same computation
print(tf.multiply(x, 2))
print(x * y)
print(x * z)

tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)
tf.Tensor([2 4 6], shape=(3,), dtype=int32)


同様に、1 にサイズ設定された次元を別の引数に一致するように引き延ばすことができます。両方の引数を同一の計算で引き延ばすことができます。

この場合、3x1 の行列は、要素ごとに 1x4 の行列と乗算され、3x4 の行列が生成されます。最初の 1 はオプションであることに注意してください。形状 y は `[4]` です。

In [ ]:
# These are the same computations
x = tf.reshape(x,[3,1])
y = tf.range(1, 5)
print(x, "\n")
print(y, "\n")
print(tf.multiply(x, y))

tf.Tensor(
[[1]
 [2]
 [3]], shape=(3, 1), dtype=int32) 

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32) 

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


<table>
<tr>
  <th>ブロードキャストの加算: <code>[3, 1]</code> 掛け <code>[1, 4]</code> により、<code>[3,4]</code> を生成</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/broadcasting.png?raw=1" alt="Adding a 3x1 matrix to a 4x1 matrix results in a 3x4 matrix">   </td>
</tr>
</table>


次は、ブロードキャストを使用しない同一の演算です。

In [ ]:
x_stretch = tf.constant([[1, 1, 1, 1],
                         [2, 2, 2, 2],
                         [3, 3, 3, 3]])

y_stretch = tf.constant([[1, 2, 3, 4],
                         [1, 2, 3, 4],
                         [1, 2, 3, 4]])

print(x_stretch * y_stretch)  # Again, operator overloading

tf.Tensor(
[[ 1  2  3  4]
 [ 2  4  6  8]
 [ 3  6  9 12]], shape=(3, 4), dtype=int32)


ブロードキャスト演算によってメモリ内の拡張したテンソルが実体化されることがないため、ほとんどの場合、ブロードキャストは時間と空間係数の両方です。

`tf.broadcast_to` を使用して、ブロードキャストがどのようなものであるかを確認します。

In [ ]:
print(tf.broadcast_to(tf.constant([1, 2, 3]), [3, 3]))

tf.Tensor(
[[1 2 3]
 [1 2 3]
 [1 2 3]], shape=(3, 3), dtype=int32)


たとえば数学的演算とは異なり、`broadcast_to` はメモリを節約する上で何も特別なことは実行しません。ここでは、テンソルの実体化が行われています。

さらに複雑化することができます。Jake VanderPlas の書籍『*Python Data Science Handbook*』の[このセクション](https://jakevdp.github.io/PythonDataScienceHandbook/02.05-computation-on-arrays-broadcasting.html)では、ブロードキャストのコツがさらに紹介されています（やはり NumPy で）。

## tf.convert_to_tensor

`tf.matmul` や `tf.reshape` といったほとんどの演算は、クラス `tf.Tensor` の引数を取りますが、上記の例では、テンソルのような形状の Python オブジェクトを渡すことがよくあります。

すべてではありませんが、ほとんどの演算は、非テンソル引数に対して `convert_to_tensor` を呼び出します。変換のレジストリがあり、NumPy の `ndarray`、`TensorShape`、Python リスト、`tf.Variable` といったほとんどのオブジェクトクラスは、自動的に変換されます。

詳細について、または、テンソルに自動変換する独自の型がある場合は、`tf.register_tensor_conversion_function` を参照してください。

## 不規則なテンソル

軸に合わせて要素の数が変化するテンソルは「不規則」と呼ばれています。不規則なデータには、`tf.ragged.RaggedTensor` を使用してください。

たとえば、次の形状は通常のテンソルとして表現することはできません。

<table>
<tr>
  <th>`tf.RaggedTensor`, 形状: <code>[4, None]</code>
</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/ragged.png?raw=1" alt="A 2-axis ragged tensor, each row can have a different length.">
</td>
</tr>
</table>

In [ ]:
ragged_list = [
    [0, 1, 2, 3],
    [4, 5],
    [6, 7, 8],
    [9]]

In [ ]:
try:
  tensor = tf.constant(ragged_list)
except Exception as e:
  print(f"{type(e).__name__}: {e}")

ValueError: Can't convert non-rectangular Python sequence to Tensor.


代わりに、`tf.ragged.constant` を使用して `tf.RaggedTensor` を作成します。

In [ ]:
ragged_tensor = tf.ragged.constant(ragged_list)
print(ragged_tensor)

<tf.RaggedTensor [[0, 1, 2, 3], [4, 5], [6, 7, 8], [9]]>


`tf.RaggedTensor` の形状には不明な次元が含まれます。

In [ ]:
print(ragged_tensor.shape)

(4, None)


## 文字列型テンソル

`tf.string` は `dtype` であるため、テンソルで文字列（可変長バイト配列）としてデータを表すことができます。

文字列はアトミックであり、Python 文字列のようにインデックスを作成することはできません。文字列の長さはテンソルの次元の 1 つではありません。これらを操作するための関数については、`tf.strings` を参照してください。

次はスカラー文字列のテンソルです。

In [ ]:
# Tensors can be strings, too here is a scalar string.
scalar_string_tensor = tf.constant("Gray wolf")
print(scalar_string_tensor)

tf.Tensor(b'Gray wolf', shape=(), dtype=string)


そして、ベクトルの文字列です。

<table>
<tr>
  <th>文字列ベクトル, 形状: <code>[3,]</code>
</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/strings.png?raw=1" alt="The string length is not one of the tensor's axes.">
</td>
</tr>
</table>

In [ ]:
# If you have three string tensors of different lengths, this is OK.
tensor_of_strings = tf.constant(["Gray wolf",
                                 "Quick brown fox",
                                 "Lazy dog"])
# Note that the shape is (3,). The string length is not included.
print(tensor_of_strings)

tf.Tensor([b'Gray wolf' b'Quick brown fox' b'Lazy dog'], shape=(3,), dtype=string)


上記の出力では、プレフィクス `b` は `tf.string` dtype が unicode 文字列でなくバイト文字列であることを示します。TensorFlow での Unicode テキストの使用については、「[Unicode チュートリアル](https://www.tensorflow.org/tutorials/load_data/unicode)」 を参照してください。

Unicode 文字を渡した場合、utf-8 で暗号化されます。

In [ ]:
tf.constant("🥳👍")

<tf.Tensor: shape=(), dtype=string, numpy=b'\xf0\x9f\xa5\xb3\xf0\x9f\x91\x8d'>

文字列の基本的な関数は、`tf.strings.split` などの `tf.strings` を使って見つけることができます。

In [ ]:
# We can use split to split a string into a set of tensors
print(tf.strings.split(scalar_string_tensor, sep=" "))

tf.Tensor([b'Gray' b'wolf'], shape=(2,), dtype=string)


In [ ]:
# ...but it turns into a `RaggedTensor` if we split up a tensor of strings,
# as each string might be split into a different number of parts.
print(tf.strings.split(tensor_of_strings))

<tf.RaggedTensor [[b'Gray', b'wolf'], [b'Quick', b'brown', b'fox'], [b'Lazy', b'dog']]>


<table>
<tr>
  <th> 3 文字列分割, 形状: <code>[3, None]</code>
</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/string-split.png?raw=1" alt="Splitting multiple strings returns a tf.RaggedTensor">
</td>
</tr>
</table>

また、`tf.string.to_number` も利用できます。

In [ ]:
text = tf.constant("1 10 100")
print(tf.strings.to_number(tf.strings.split(text, " ")))

tf.Tensor([  1.  10. 100.], shape=(3,), dtype=float32)


`tf.cast` を使用して文字列テンソルを数値に変換することはできませんが、バイトに変換してから数字に変換することができます。

In [ ]:
byte_strings = tf.strings.bytes_split(tf.constant("Duck"))
byte_ints = tf.io.decode_raw(tf.constant("Duck"), tf.uint8)
print("Byte strings:", byte_strings)
print("Bytes:", byte_ints)

Byte strings: tf.Tensor([b'D' b'u' b'c' b'k'], shape=(4,), dtype=string)
Bytes: tf.Tensor([ 68 117  99 107], shape=(4,), dtype=uint8)


In [ ]:
# Or split it up as unicode and then decode it
unicode_bytes = tf.constant("アヒル 🦆")
unicode_char_bytes = tf.strings.unicode_split(unicode_bytes, "UTF-8")
unicode_values = tf.strings.unicode_decode(unicode_bytes, "UTF-8")

print("\nUnicode bytes:", unicode_bytes)
print("\nUnicode chars:", unicode_char_bytes)
print("\nUnicode values:", unicode_values)


Unicode bytes: tf.Tensor(b'\xe3\x82\xa2\xe3\x83\x92\xe3\x83\xab \xf0\x9f\xa6\x86', shape=(), dtype=string)

Unicode chars: tf.Tensor([b'\xe3\x82\xa2' b'\xe3\x83\x92' b'\xe3\x83\xab' b' ' b'\xf0\x9f\xa6\x86'], shape=(5,), dtype=string)

Unicode values: tf.Tensor([ 12450  12498  12523     32 129414], shape=(5,), dtype=int32)


TensorFlow ではすべての生のバイトに、`tf.string` dtype が使用されています。`tf.io` モジュールには、画像の解読や csv の解析など、データとバイトを変換する関数が含まれています。

## スパーステンソル

非常に広い埋め込みスペースであるかのうように、データがスパースである場合があります。TensorFlow は、スパースデータを効率的に保管できるように、`tf.sparse.SparseTensor` と関連する演算をサポートしています。

<table>
<tr>
  <th>`tf.SparseTensor`, 形状: <code>[3, 4]</code>
</th>
</tr>
<tr>
  <td> <img src="https://github.com/tensorflow/docs-l10n/blob/master/site/ja/guide/images/tensor/sparse.png?raw=1" alt="An 3x4 grid, with values in only two of the cells.">   </td>
</tr>
</table>

In [ ]:
# Sparse tensors store values by index in a memory-efficient manner
sparse_tensor = tf.sparse.SparseTensor(indices=[[0, 0], [1, 2]],
                                       values=[1, 2],
                                       dense_shape=[3, 4])
print(sparse_tensor, "\n")

# We can convert sparse tensors to dense
print(tf.sparse.to_dense(sparse_tensor))

SparseTensor(indices=tf.Tensor(
[[0 0]
 [1 2]], shape=(2, 2), dtype=int64), values=tf.Tensor([1 2], shape=(2,), dtype=int32), dense_shape=tf.Tensor([3 4], shape=(2,), dtype=int64)) 

tf.Tensor(
[[1 0 0 0]
 [0 0 2 0]
 [0 0 0 0]], shape=(3, 4), dtype=int32)
